name: stacked_playground
description: Demo for Stacked architecture
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Architecture
  stacked: ^3.0.0
  stacked_services: ^0.9.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  logger: ^1.1.0
  # REST
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.7.0
  # UI
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.2
  figma_squircle: ^0.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  # Architecture
  stacked_generator: ^0.8.0
  injectable_generator: ^1.5.4
  # REST
  retrofit_generator: ^4.1.0+1
  json_serializable: ^6.4.0
flutter:
  uses-material-design: true
